In [1]:
import gym

In [2]:
env=gym.make("CartPole-v0")

In [6]:
env.reset()#these are just position,velocity,angle,velocity at tip

array([-0.0083846 ,  0.04691236,  0.00787847, -0.01912457])

In [8]:
box=env.observation_space

In [13]:
box.low

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

In [15]:
env.action_space.n

2

In [16]:
done= False
while not done:
    observation,reward,done,_ = env.step(env.action_space.sample())


In [17]:
from __future__ import print_function, division
from builtins import range
# Note: you may need to update your version of future
# sudo pip install -U future

import gym
import numpy as np
import matplotlib.pyplot as plt


def get_action(s, w):
  return 1 if s.dot(w) > 0 else 0


def play_one_episode(env, params):
  observation = env.reset()
  done = False
  t = 0

  while not done and t < 10000:
    # env.render()
    t += 1
    action = get_action(observation, params)
    observation, reward, done, info = env.step(action)
    if done:
      break

  return t


def play_multiple_episodes(env, T, params):
  episode_lengths = np.empty(T)

  for i in range(T):
    episode_lengths[i] = play_one_episode(env, params)

  avg_length = episode_lengths.mean()
  print("avg length:", avg_length)
  return avg_length


def random_search(env):
  episode_lengths = []
  best = 0
  params = None
  for t in range(100):
    new_params = np.random.random(4)*2 - 1
    avg_length = play_multiple_episodes(env, 100, new_params)
    episode_lengths.append(avg_length)

    if avg_length > best:
      params = new_params
      best = avg_length
  return episode_lengths, params


if __name__ == '__main__':
  env = gym.make('CartPole-v0')
  episode_lengths, params = random_search(env)
  plt.plot(episode_lengths)
  plt.show()

  # play a final set of episodes
  print("***Final run with final weights***")
  play_multiple_episodes(env, 100, params)

avg length: 9.48
avg length: 9.15
avg length: 110.38
avg length: 9.26
avg length: 19.28
avg length: 56.22
avg length: 9.0
avg length: 9.25
avg length: 47.42
avg length: 79.92
avg length: 25.78
avg length: 9.39
avg length: 33.37
avg length: 118.74
avg length: 186.31
avg length: 96.32
avg length: 199.75
avg length: 9.6
avg length: 47.21
avg length: 9.43
avg length: 8.99
avg length: 94.82
avg length: 9.49
avg length: 78.61
avg length: 80.69
avg length: 36.21
avg length: 9.68
avg length: 9.45
avg length: 8.97
avg length: 9.27
avg length: 9.19
avg length: 8.94
avg length: 9.3
avg length: 74.77
avg length: 39.1
avg length: 115.46
avg length: 133.68
avg length: 9.72
avg length: 200.0
avg length: 9.36
avg length: 48.07
avg length: 133.04
avg length: 9.19
avg length: 9.58
avg length: 9.18
avg length: 24.72
avg length: 9.74
avg length: 9.36
avg length: 56.12
avg length: 70.57
avg length: 51.37
avg length: 71.43
avg length: 9.24
avg length: 200.0
avg length: 190.66
avg length: 9.11
avg length: 18

<Figure size 640x480 with 1 Axes>

***Final run with final weights***
avg length: 200.0


In [18]:
np.random.random(4)*2 - 1

array([-0.85346453, -0.62918261,  0.84426377, -0.74902273])